site_name: DevOpsVaultX Docs
site_url: https://docs.devopsvaultx.com/

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy

  palette:
    scheme: default
    primary: indigo
    accent: indigo

plugins:
  - search

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2026 <strong>DevOpsVaultX</strong> | <span style="color: #10b981;">Code. Deploy. Automate. Repeat.</span> ❤️

nav:
  - Home: index.md

  - Linux:
    - linux/index.md
    - Architecture: linux/architecture.md
    - Installations: linux/installation.md
    - Commands: linux/commands.md

  - Git:
    - git/index.md
    - Architecture: git/architecture.md
    - Installations: git/installation.md
    - Commands: git/commands.md

  - GitHub:
    - github/index.md
    - Architecture: github/architecture.md
    - Installations: github/installation.md
    - Commands: github/commands.md

  - Docker:
    - docker/index.md
    - Architecture: docker/architecture.md
    - Installations: docker/installation.md
    - Commands: docker/commands.md

  - CI/CD:
    - cicd/index.md
    - Architecture: cicd/architecture.md
    - Installations: cicd/installation.md
    - Commands: cicd/commands.md

  - GitHub Actions:
    - github_actions/index.md
    - Architecture: github_actions/architecture.md
    - Installations: github_actions/installation.md
    - Commands: github_actions/commands.md

  - Azure DevOps:
    - azure_devops/index.md
    - Architecture: azure_devops/architecture.md
    - Installations: azure_devops/installation.md
    - Commands: azure_devops/commands.md

  - Kubernetes:
    - kubernetes/index.md
    - Architecture: kubernetes/architecture.md
    - Installations:
        - Kind Installation: kubernetes/kind.md
        - Minikube Installation: kubernetes/minikube.md
    - Commands: kubernetes/commands.md
    - RBAC: kubernetes/rbac.md
    - K8S Probes: kubernetes/probes.md

  - Terraform:
    - terraform/index.md
    - Architecture: terraform/architecture.md
    - Installations: terraform/installation.md
    - Commands: terraform/commands.md

  - Ansible:
    - ansible/index.md
    - Architecture: ansible/architecture.md
    - Installations: ansible/installation.md
    - Commands: ansible/commands.md

  - Azure:
    - azure/index.md
    - Architecture: azure/architecture.md
    - Installations: azure/installation.md
    - Commands: azure/commands.md

  - AWS:
    - aws/index.md
    - Architecture: aws/architecture.md
    - Installations: aws/installation.md
    - Commands: aws/commands.md

  - Observability:
    - observability/index.md
    - Architecture: observability/architecture.md
    - Installations: observability/installation.md
    - Commands: observability/commands.md

  - DevSecOps:
    - devsecops/index.md
    - Architecture: devsecops/architecture.md
    - Installations: devsecops/installation.md
    - Commands: devsecops/commands.md

  - GitOps:
    - gitops/index.md
    - Architecture: gitops/architecture.md
    - Installations: gitops/installation.md
    - Commands: gitops/commands.md

  - Helm:
    - helm/index.md
    - Architecture: helm/architecture.md
    - Installations: helm/installation.md
    - Commands: helm/commands.md

  - Interview Questions:
    - interview_questions/index.md
    - Linux: interview_questions/linux.md
    - Git: interview_questions/git.md
    - GitHub: interview_questions/github.md
    - Docker: interview_questions/docker.md
    - CI/CD: interview_questions/cicd.md
    - GitHub Actions: interview_questions/github_actions.md
    - Azure DevOps: interview_questions/azure_devops.md
    - Kubernetes: interview_questions/kubernetes.md
    - Terraform: interview_questions/terraform.md
    - Ansible: interview_questions/ansible.md
    - Azure: interview_questions/azure.md
    - AWS: interview_questions/aws.md
    - Observability: interview_questions/observability.md
    - DevSecOps: interview_questions/devsecops.md